DESIGNDB_DIR := extern/RTLDebugDBKit
DESIGNDB_BIN := $(DESIGNDB_DIR)/build/rtl-designdb

.PHONY: build test test-exporter test-cores check designdb sync-ddl examples

build:
	cargo build

# The tests that need an exporter skip without one; `make test-exporter` is
# the run that refuses to.
test:
	cargo test --all-targets

# Every test, with the ones that go through rtl-designdb made mandatory: a run
# meant to cover them must not pass by not running them.
test-exporter: $(DESIGNDB_BIN)
	RTL_DESIGNDB=$(abspath $(DESIGNDB_BIN)) RTLSCANNER_REQUIRE_EXPORTER=1 \
		cargo test --all-targets

# The strictest run: the invariants over real cores as well. CORES is a
# directory holding their checkouts, one per core — which ones, and what the
# exporter is told about each, is in crates/rtlscanner/tests/real_cores.rs.
test-cores: $(DESIGNDB_BIN)
	@test -n "$(CORES)" || { echo "set CORES=<directory holding the core checkouts>"; exit 1; }
	RTL_DESIGNDB=$(abspath $(DESIGNDB_BIN)) RTLSCANNER_REQUIRE_EXPORTER=1 \
		RTLSCANNER_CORES=$(abspath $(CORES)) RTLSCANNER_REQUIRE_CORES=1 \
		cargo test --all-targets

# Regenerate the worked answers in examples/. They are the shape of an answer
# an agent sees before asking for one, and a hand-kept copy of that shape drifts
# silently — so it is generated, and a test regenerates it to compare.
examples: $(DESIGNDB_BIN)
	RTL_DESIGNDB=$(abspath $(DESIGNDB_BIN)) RTLSCANNER_REQUIRE_EXPORTER=1 \
		RTLSCANNER_WRITE_EXAMPLES=1 cargo test --test examples -- --nocapture

check:
	cargo clippy --all-targets -- -D warnings
	cargo fmt --check

designdb: $(DESIGNDB_BIN)

# No --depth 1: the submodule is pinned to a commit, and a shallow fetch can
# only reach the default branch's tip. It works exactly until the pin stops
# being that tip, which is the point at which pinning starts to matter.
$(DESIGNDB_BIN):
	git submodule update --init $(DESIGNDB_DIR)
	cmake -B $(DESIGNDB_DIR)/build -S $(DESIGNDB_DIR) -DCMAKE_BUILD_TYPE=Release
	cmake --build $(DESIGNDB_DIR)/build -j

# Re-extract the DDL the test fixtures build their databases from, and refuse
# to leave it disagreeing with the version this reader accepts. The SQL carries
# no version of its own, so nothing else would catch v20's DDL sitting under a
# reader pinned to 19 — every test would still pass, against a database shaped
# like neither.
#
# The exporter marks its enum CHECK clauses with /*!*/ so it can leave them out
# for speed; the markers are stripped and the clauses kept, because a fixture
# that could insert an out-of-domain enum word would be testing against a
# database the kit never writes.
sync-ddl:
	@kit=$$(sed -n 's/.*SchemaVersion = \([0-9]*\).*/\1/p' $(DESIGNDB_DIR)/src/DesignDb.h); \
	mine=$$(sed -n 's/.*SCHEMA_VERSION: i64 = \([0-9]*\).*/\1/p' crates/designdb/src/open.rs); \
	if [ "$$kit" != "$$mine" ]; then \
		echo "the submodule is schema v$$kit and this reader accepts v$$mine."; \
		echo "update SCHEMA_VERSION in crates/designdb/src/open.rs, then run this again."; \
		exit 1; \
	fi; \
	rev=$$(git -C $(DESIGNDB_DIR) rev-parse --short HEAD); \
	for pair in Schema:schema Indexes:indexes Views:views; do \
		src=$${pair%%:*}; dst=$${pair##*:}; \
		{ echo "-- Extracted from RTLDebugDBKit src/sql/$$src.inc @ $$rev (schema v$$kit)."; \
		  echo "-- Generated by 'make sync-ddl'; do not edit."; \
		  awk '/^R"SQL\($$/{p=1;next} /^\)SQL"$$/{p=0} p' \
			$(DESIGNDB_DIR)/src/sql/$$src.inc | sed 's|/\*!\*/||g'; \
		} > crates/designdb/src/ddl/$$dst.sql; \
	done; \
	echo "DDL extracted at schema v$$kit ($$rev)"
