DESIGNDB_DIR := extern/RTLDebugDBKit

.PHONY: build test check designdb sync-ddl

build:
	cargo build

# --all-targets covers every compiled target and excludes doctests, of which
# this workspace has none.
test:
	cargo test --all-targets

check:
	cargo clippy --all-targets -- -D warnings
	cargo fmt --check

# Build rtl-designdb from the pinned submodule. Slow the first time: the build
# fetches and compiles slang. Where a release binary is available, put it on
# PATH instead.
designdb:
	git submodule update --init --depth 1 $(DESIGNDB_DIR)
	cmake -B $(DESIGNDB_DIR)/build -S $(DESIGNDB_DIR) -DCMAKE_BUILD_TYPE=Release
	cmake --build $(DESIGNDB_DIR)/build -j
	@echo "built $(DESIGNDB_DIR)/build/rtl-designdb"

# Re-extract the DDL the test fixtures build their databases from, and report
# the schema version it belongs to. Run this when the submodule moves.
#
# The exporter marks its enum CHECK clauses with /*!*/ so it can leave them out
# for speed; the markers are stripped and the clauses kept, because a fixture
# that could insert an out-of-domain enum word would be testing against a
# database the kit never writes.
sync-ddl:
	@rev=$$(git -C $(DESIGNDB_DIR) rev-parse --short HEAD); \
	ver=$$(sed -n 's/.*SchemaVersion = \([0-9]*\).*/\1/p' $(DESIGNDB_DIR)/src/DesignDb.h); \
	for pair in Schema:schema Indexes:indexes Views:views; do \
		src=$${pair%%:*}; dst=$${pair##*:}; \
		{ echo "-- Extracted from RTLDebugDBKit src/sql/$$src.inc @ $$rev (schema v$$ver)."; \
		  echo "-- Generated by 'make sync-ddl'; do not edit."; \
		  awk '/^R"SQL\($$/{p=1;next} /^\)SQL"$$/{p=0} p' \
			$(DESIGNDB_DIR)/src/sql/$$src.inc | sed 's|/\*!\*/||g'; \
		} > crates/designdb/src/ddl/$$dst.sql; \
	done
	@grep -n 'SchemaVersion = ' $(DESIGNDB_DIR)/src/DesignDb.h
	@grep -n 'SCHEMA_VERSION: i64' crates/designdb/src/open.rs
	@echo "the two versions above must agree"
