-- Extracted from RTLDebugDBKit src/sql/Schema.inc @ 7ccde09 (schema v20).
-- Generated by 'make sync-ddl'; do not edit.

-- The seal: one row, one column per fact. Each of these is required, typed,
-- and exactly one per database, and a key/value table could say none of that
-- -- presence was the verifier's to check, the counts were TEXT a view had to
-- CAST, and a mistyped key became a seventeenth fact instead of an error.
--
-- This table keeps its CHECKs where the enum columns elsewhere do not: the
-- per-row cost that rules them out is one row here.
CREATE TABLE db_info(
    id                    INTEGER PRIMARY KEY CHECK(id = 1),
    schema_version        INTEGER NOT NULL,
    tool                  TEXT NOT NULL,
    tool_version          TEXT NOT NULL,
    slang_version         TEXT NOT NULL,
    producer_revision     TEXT NOT NULL,
    -- The ELABORATED tops, space-separated; NULL when the design elaborated
    -- none. Every other column is a fact about the run and always there.
    top                   TEXT,
    analysis_status       TEXT NOT NULL
        CHECK(analysis_status IN ('complete','partial','hierarchy_only')),
    error_count           INTEGER NOT NULL,
    unresolved_count      INTEGER NOT NULL,
    empty_procedure_count INTEGER NOT NULL,
    duplicate_path_count  INTEGER NOT NULL,
    recursion_count       INTEGER NOT NULL,
    truncated_call_count  INTEGER NOT NULL,
    checker_inst_count    INTEGER NOT NULL,
    unanalysed_inst_count INTEGER NOT NULL,
    config_digest         TEXT NOT NULL,
    -- The status agrees with the counts beside it, which was prose in the
    -- exporter and an assertion in the verifier and a rule the file itself
    -- could not hold. `hierarchy_only` is exempt because it is decided before
    -- any count is taken: the compilation was fatally errored, so there was
    -- no dataflow to count gaps in.
    CHECK(analysis_status = 'hierarchy_only'
          OR (analysis_status = 'complete') =
             (error_count = 0 AND empty_procedure_count = 0 AND
              duplicate_path_count = 0 AND truncated_call_count = 0 AND
              unanalysed_inst_count = 0))
) STRICT;

CREATE TABLE src_file(
    id      INTEGER PRIMARY KEY,
    path    TEXT UNIQUE,
    digest  TEXT);

-- `path` is the spelling the rows carry -- as written in the filelist or on
-- the command line -- while `src_file.path` is absolute. The two genuinely
-- differ, so `src_file_id` joins them: without it a consumer checking
-- digests had to match spellings by basename, which breaks on the first
-- design with two files of one name.
CREATE TABLE file(
    id             INTEGER PRIMARY KEY,
    path           TEXT UNIQUE,
    src_file_id    INTEGER REFERENCES src_file(id));

-- Repeated type text, interned -- the one intern table v10 keeps. A packed
-- struct or enum prints as its entire member list, far larger than the row
-- referencing it, and the instance-level model repeats each declaration once
-- per occurrence. Names are not interned: they are short, and the join every
-- query paid the old `name` table was the storage tail wagging the schema.
CREATE TABLE data_type(id INTEGER PRIMARY KEY, text TEXT UNIQUE);

-- A source definition: what was written, not what it elaborated into. The
-- parameter values a body elaborated with are per-occurrence facts and live
-- on `inst.param_signature` -- v9 folded them into module identity, v10
-- puts identity where the source has it. (name, file_id, line) is the
-- definition's own identity; two libraries may define one name.
CREATE TABLE module(
    id              INTEGER PRIMARY KEY,
    name            TEXT NOT NULL,
    def_kind        TEXT NOT NULL,
    file_id         INTEGER REFERENCES file(id),
    line            INTEGER,
    col             INTEGER,
    UNIQUE(name, file_id, line));

-- The hierarchy tree, one node per level, one path segment per node --
-- resolving `a.b[0].c` is one indexed lookup per segment, which is why the
-- paths themselves are never stored. This is the supertype: a module
-- instance is a `tree_node` plus an `inst` row under the same id, a gate is
-- a `tree_node` plus a `primitive` row, a generate block is a bare
-- `tree_node`. node_kind says which, and the verifier holds the bijection.
--
--   root        the top instance; it has an `inst` row and no parent.
--   instance    a resolved module/interface/program instance -> `inst`.
--   generate    a generate block or one element of a generate array. A
--               naming level, not an object; nothing subtypes it.
--   primitive   a gate, switch or UDP -> `primitive`.
--   unresolved  an instance whose definition slang could not find -> `inst`
--               with module_id NULL. A trace really does stop here.
--   package     a package (or the compilation unit's `$unit` scope), a
--               pseudo-occurrence above the roots -> `inst` with
--               parent_inst_id NULL and a `module` of def_kind 'package'.
--               Its variables are `net` rows, so a `pkg::x` reference
--               resolves to a real object instead of leaving the model.
CREATE TABLE tree_node(
    id             INTEGER PRIMARY KEY,
    parent_node_id INTEGER REFERENCES tree_node(id),
    name           TEXT NOT NULL,
    node_kind      TEXT NOT NULL,
    ordinal        INTEGER NOT NULL);

-- One module instance occurrence. `id` IS the tree_node id -- one id space
-- for the whole hierarchy, so `net.inst_id` and `tree_node.parent_node_id`
-- never disagree about what an instance is.
--
-- `parent_inst_id` is the nearest enclosing module instance, skipping
-- generate levels -- the ancestry `tree_node` already encodes, denormalised
-- one hop because every ownership check walks it. The verifier holds the two
-- encodings equal.
--
-- `param_signature` is the elaborated parameter values, normalised, in
-- declaration order, localparams included (it over-splits, never
-- under-splits). Instances of one module with one signature share a body and
-- carry identical rows -- the sharing v9 stored once, v10 stamps out.
CREATE TABLE inst(
    id                    INTEGER PRIMARY KEY REFERENCES tree_node(id),
    module_id             INTEGER REFERENCES module(id),
    parent_inst_id        INTEGER REFERENCES inst(id),
    param_signature       TEXT,
    unresolved_def        TEXT,
    file_id               INTEGER REFERENCES file(id),
    line                  INTEGER,
    col                   INTEGER);

-- param_signature made queryable: one row per elaborated parameter value,
-- declaration order, localparams and type parameters included -- the same
-- normalisation the signature is built from, and the verifier holds the
-- two representations equal. "Every instance with WIDTH=8" was a LIKE
-- over the signature (and matched XWIDTH=8); now it is an indexed seek.
CREATE TABLE inst_param(
    inst_id  INTEGER NOT NULL REFERENCES inst(id),
    ordinal  INTEGER NOT NULL,
    name     TEXT NOT NULL,
    value    TEXT NOT NULL,
    PRIMARY KEY(inst_id, ordinal));

-- One gate, switch or UDP instance. `id` IS the tree_node id. Not a module
-- instance (it has no body, no ports, no parameters) and not a statement
-- (nothing was assigned); its dataflow is `net_dep` rows with
-- prim_id set. Expression operators (`&`, `+`, `?:`) are not
-- primitives -- they stay inside their statement's own rows.
CREATE TABLE prim(
    id              INTEGER PRIMARY KEY REFERENCES tree_node(id),
    inst_id         INTEGER NOT NULL REFERENCES inst(id),
    prim_kind       TEXT NOT NULL,
    def_name        TEXT NOT NULL,
    file_id         INTEGER REFERENCES file(id),
    line            INTEGER,
    col             INTEGER);

-- One connectable object in one instance: a net or a variable -- anything
-- that can be driven, read or wired. `name` is the dotted path relative to
-- inst_id, generate and subroutine segments included (`g[0].sig`), so a
-- net's full path is its INSTANCE's tree path plus `name`. scope_node_id is
-- the node that declares it -- the filter for "signals of this scope",
-- never the name's anchor: prefixing the scope node's path onto `name`
-- counts every generate segment twice. Parameters, type parameters and
-- interface ports are NOT here: they are not connectable, and v9 mixing them
-- into `symbol` made every "signals of this scope" query filter them out.
--
-- Subroutine formals and locals ARE here (name spells the subroutine
-- segment, `bump.v`): a call binds actuals to formals and `net_dep` ends are
-- ids, so a formal without a row would be a dependency with a dangling end.
-- Their scope_node_id is the nearest tree_node, since a subroutine is not a
-- hierarchy level.
--
-- decl_kind is the net type's own word (`wire`, `wand`, `trireg`,
-- ...) or `variable`. is_implicit=1 marks a net slang created for an
-- undeclared identifier under the active `default_nettype`; its
-- decl_kind is that nettype, and its location is the first use.
CREATE TABLE net(
    id               INTEGER PRIMARY KEY,
    inst_id          INTEGER NOT NULL REFERENCES inst(id),
    scope_node_id    INTEGER NOT NULL REFERENCES tree_node(id),
    name             TEXT NOT NULL,
    decl_kind        TEXT NOT NULL,
    data_type_id     INTEGER REFERENCES data_type(id),
    width            INTEGER,
    is_implicit      INTEGER NOT NULL CHECK(is_implicit IN (0,1)),
    file_id          INTEGER REFERENCES file(id),
    line             INTEGER,
    col              INTEGER);

-- One terminal: a port on an instance's boundary. The root instance's
-- terminals are the design's top-level ports; a child's are the pins its
-- parent connects. One noun for both, because they are the same object seen
-- from the two sides v9 conflated in one `port` row.
--
-- direction is NULL for an interface terminal (it has none) and for a
-- terminal of an unresolved instance (nobody knows). is_const marks
-- `const ref`; NULL where constness does not apply. An unresolved instance
-- still gets terminal rows -- one per connection its parent wrote, named as
-- the connection names them -- so `net_conn` has something to bind and
-- "connected to a black box" stays distinct from "connected to nothing".
CREATE TABLE term(
    id            INTEGER PRIMARY KEY,
    inst_id       INTEGER NOT NULL REFERENCES inst(id),
    name          TEXT NOT NULL,
    term_kind     TEXT NOT NULL,
    direction     TEXT,
    data_type_id  INTEGER REFERENCES data_type(id),
    width         INTEGER,
    ordinal       INTEGER NOT NULL,
    modport       TEXT,
    file_id       INTEGER REFERENCES file(id),
    line          INTEGER,
    col           INTEGER);

-- The INSIDE of a terminal: which nets of its own instance it stands for,
-- one row per segment. An ANSI port is one whole-to-whole row; a non-ANSI
-- `.p({hi, lo})` formal is one row per element, each with its window of the
-- terminal (`term_lo`/`term_hi`) and of the net. Both nets belong to the
-- terminal's own instance -- the outside is `net_conn`'s business, and
-- keeping the two relations apart is what v9's one-table version kept
-- getting wrong.
CREATE TABLE term_map(
    id            INTEGER PRIMARY KEY,
    term_id       INTEGER NOT NULL REFERENCES term(id),
    ordinal       INTEGER NOT NULL,
    inner_net_id  INTEGER NOT NULL REFERENCES net(id),
    term_lo       INTEGER,
    term_hi       INTEGER,
    term_exact    INTEGER NOT NULL CHECK(term_exact IN (0,1)),
    inner_lo      INTEGER,
    inner_hi      INTEGER,
    inner_exact   INTEGER NOT NULL CHECK(inner_exact IN (0,1)),
    map_exact     INTEGER NOT NULL CHECK(map_exact IN (0,1)),
    UNIQUE(term_id, ordinal));

-- The OUTSIDE of a terminal: what the parent connected to it, one row per
-- atomic segment -- each concatenation element and each replication copy is
-- its own row with its own window of the formal, so `.q({2{r}})` is two
-- rows whose windows tile q. conn_kind decides which columns apply:
--
--   signal              outer_net_id names a net of the PARENT instance.
--   constant            a tie-off; no net, but the window is kept so the
--                       formal's bits tile rather than leaving a gap that
--                       reads as an exporter bug.
--   unconnected         nobody connected it. Recorded, not omitted: absence
--                       would also mean "the exporter did not get this far".
--   expression_operand  the actual is an expression; this row is one net it
--                       reads. `.en(state == RUN)` samples state but does
--                       not alias it to en -- map_exact is 0 by
--                       construction.
--   interface           outer_intf_inst_id names the bound interface
--                       instance. No dataflow arc pretends to cross here.
--   external_reference  tied to something with no name in the parent
--                       (`.p(u.g[7:4])`); outer_hier_ref_id says what, and
--                       the arc crosses once that reference resolves.
--
-- Range discipline: columns describing an end that does not exist are NULL
-- -- a constant has no net end, an interface binding has no bit domain --
-- so a tie-off never reads as "the whole of nothing, exactly".
CREATE TABLE net_conn(
    id                 INTEGER PRIMARY KEY,
    outer_net_id       INTEGER REFERENCES net(id),
    term_id            INTEGER NOT NULL REFERENCES term(id),
    ordinal            INTEGER NOT NULL,
    conn_kind          TEXT NOT NULL,
    outer_lo           INTEGER,
    outer_hi           INTEGER,
    outer_exact        INTEGER CHECK(outer_exact IN (0,1)),
    term_lo            INTEGER,
    term_hi            INTEGER,
    term_exact         INTEGER CHECK(term_exact IN (0,1)),
    map_exact          INTEGER CHECK(map_exact IN (0,1)),
    outer_intf_inst_id INTEGER REFERENCES inst(id),
    outer_hier_ref_id  INTEGER REFERENCES hier_ref(id),
    file_id            INTEGER REFERENCES file(id),
    line               INTEGER,
    col                INTEGER,
    UNIQUE(term_id, ordinal));

-- One procedure: an always/initial/final block. Task and function bodies
-- get no row; their statements belong to the calling procedure. v9 named
-- these with a bare per-module integer that was not a key in any table;
-- this is the object that integer was gesturing at.
CREATE TABLE proc(
    id             INTEGER PRIMARY KEY,
    inst_id        INTEGER NOT NULL REFERENCES inst(id),
    scope_node_id  INTEGER NOT NULL REFERENCES tree_node(id),
    proc_kind      TEXT NOT NULL,
    ordinal        INTEGER NOT NULL,
    file_id        INTEGER REFERENCES file(id),
    line           INTEGER,
    col            INTEGER);

-- One subroutine-body expansion. A task or function body is walked once per
-- call site (its statements carry that call's gating and delay), and this is
-- that site's identity, so a consumer can partition a fan-in cone by it and
-- never mix one call's gating with another's argument -- the combination no
-- single call makes, which a shared formal net otherwise admits. `stmt` and
-- `net_dep` rows a body walk produced name their site in `call_site_id`;
-- `parent_call_site_id` chains nested calls into a call string.
--
-- caller_stmt_id is the statement making the call (NULL for a call in a
-- control expression, which this schema attaches to no statement). depth is
-- the call-stack depth, 1 at the outermost call. Additive: a reader that
-- does not know call sites ignores the column and the table.
CREATE TABLE call_site(
    id                   INTEGER PRIMARY KEY,
    inst_id              INTEGER NOT NULL REFERENCES inst(id),
    caller_stmt_id       INTEGER REFERENCES stmt(id),
    parent_call_site_id  INTEGER REFERENCES call_site(id),
    subroutine_name      TEXT NOT NULL,
    depth                INTEGER NOT NULL);

-- One level of the gating context a statement sits under: an `if` arm, a
-- case point, one case arm, a loop body. `parent_branch_id` chains them
-- outward, so a statement's conditions are the walk from `stmt.branch_id` up
-- to a root, outermost last -- the shape `call_site` already uses for nested
-- calls. Levels are SHARED: every statement in one arm names the same row,
-- and only a level that gates something has a row at all.
--
-- What each kind carries, and what is NULL beside it:
--
--   if            sense says which arm ('then'/'else'); check_kind carries a
--                 `priority if`/`unique if` qualifier. The level's control
--                 reads ARE the condition, so both arms name the same nets
--                 and `sense` is what tells the two apart.
--   case          the branch POINT, one per case statement: case_kind is the
--                 matching semantics in the LRM's word, check_kind the
--                 unique/priority qualifier, and the level's control reads
--                 are the SELECTOR's. Its children are the arms.
--   case_item     one arm. Its control reads are that item's own labels, and
--                 `branch_label` holds their evaluated values -- v18 pushed
--                 every item's labels onto one gate before walking any body,
--                 so each arm saw all of them and none could be told apart.
--                 Arms are SIBLINGS, not a chain: an arm carries its own
--                 label and not the preceding arms', so the priority a plain
--                 `case` has -- arm k is reached only if arms 0..k-1 did not
--                 match -- is `ordinal`, their written order under the point,
--                 not a read repeated onto every later arm. `ordinal` is set
--                 on exactly the arms: source line cannot carry the order,
--                 since a whole case may be written on one. It matters for
--                 the `case (1'b1)` one-hot idiom, whose labels are
--                 expressions: picorv32's decoder read `instr_trap` on 207
--                 control rows in v18 and reads it on 36 here, one per
--                 statement of the three arms whose label actually names it.
--   case_default  the `default` arm. No labels.
--   loop          a loop body. The control reads are the guard (`while`'s
--                 condition, `for`'s stop expression, `repeat`'s count), and
--                 the iter_* columns are the iteration space -- see below.
--
-- static_taken is the compile-time verdict: 1 this arm runs, 0 it cannot,
-- NULL the condition is not a constant. `localparam bit EN = 0; if (EN) …`
-- keeps its statement and its dependency rows -- the statement is in the
-- elaborated design, and a source view shows it where a pruned database
-- would not -- and says here that nothing reaches them. A consumer filtering
-- dead code excludes a statement whose level chain holds any static_taken=0.
--
-- A loop level with iter_count = 0 carries static_taken = 0: a body the
-- stop condition rejects on its first test runs never, which is the same
-- fact about reachability an unreachable arm has, and a dead-code filter
-- should read one column rather than two.
--
-- The iteration space, on a loop level, is what makes a whole-signal
-- dependency out of a loop body readable as the per-iteration mapping it is:
-- `for (int j = 0; j < 8; j++) rev[j] = din[7-j];` is ONE statement whose
-- `din -> rev` row spans both signals, and iter_net_id/iter_first/iter_step/
-- iter_count say the index j runs 0,1,…,7 so a consumer can substitute. The
-- index arithmetic itself is not here, for the same reason no expression
-- shape is: it is in the source at the location this row names. iter_step is
-- NEGATIVE where the loop counts down, which `foreach` over an ordinary
-- packed dimension does. iter_count NULL is "not statically known";
-- iter_first/iter_step are NULL together when the values are not an
-- arithmetic progression; iter_net_id is NULL for the loops that name no
-- index (`while`, `repeat`, `forever`) and for a header that names more
-- than one, which no single set of these columns describes.
--
-- A loop index is deliberately not a `data` or `control` dependency source,
-- and never an assign_operand: it takes every value of this space on the way
-- through, so `i -> hi` said the target depended on a variable no debugging
-- question reaches. Where the RTL reads it as a VALUE -- `t(i)`,
-- `$display("%d", i)` -- the read stays: it is a fact about the source, and
-- dropping it would leave a bound formal with no driver at all.
--
-- What counts as an index is a variable the header both INITIALISES and
-- STEPS. `for (k = 0, acc = 0; k < 4; k = k + 1)` initialises acc and never
-- steps it, so acc is an ordinary variable of the body and keeps every row.
CREATE TABLE branch(
    id               INTEGER PRIMARY KEY,
    inst_id          INTEGER NOT NULL REFERENCES inst(id),
    parent_branch_id INTEGER REFERENCES branch(id),
    depth            INTEGER NOT NULL,
    ordinal          INTEGER,
    branch_kind      TEXT NOT NULL,
    sense            TEXT,
    case_kind        TEXT,
    check_kind       TEXT,
    static_taken     INTEGER,
    iter_net_id      INTEGER REFERENCES net(id),
    iter_first       INTEGER,
    iter_step        INTEGER,
    iter_count       INTEGER,
    -- Where the level was walked, as `stmt.proc_id`/`stmt.call_site_id` are
    -- for a statement: a subroutine body is walked once per call site, so
    -- its levels are per expansion too -- and a level that gates nothing has
    -- no statement to borrow either answer from.
    proc_id          INTEGER REFERENCES proc(id),
    call_site_id     INTEGER REFERENCES call_site(id),
    file_id          INTEGER REFERENCES file(id),
    line             INTEGER,
    col              INTEGER);

-- One label of a case item, in written order, evaluated. `value` is the
-- elaborated constant in full precision -- the same normalisation
-- `inst_param.value` uses, not the spelling the source happened to give it
-- -- and NULL where constant evaluation does not reach the label, as for an
-- `inside` range over a variable. Such a label's reads are still control
-- reads on the item's level.
CREATE TABLE branch_label(
    id        INTEGER PRIMARY KEY,
    branch_id INTEGER NOT NULL REFERENCES branch(id),
    ordinal   INTEGER NOT NULL,
    value     TEXT,
    UNIQUE(branch_id, ordinal));

-- One read of one level's condition. The level owns it: a condition is
-- written once and evaluated once, however many statements sit under it, and
-- a level that gates nothing at all still reads what it reads -- `if (c) ;`
-- recorded c nowhere. Filing a copy per gated statement instead cost three
-- to six times the rows on real designs and still could not say that.
--
-- What a statement gets is the DEPENDENCY, one per target, naming the level
-- it came from (`net_dep.branch_id`). "Everything gating this statement" is
-- the level chain from `stmt.branch_id` outward, which `branch_ancestor`
-- makes one join.
CREATE TABLE branch_ref(
    id        INTEGER PRIMARY KEY,
    branch_id INTEGER NOT NULL REFERENCES branch(id),
    ordinal   INTEGER NOT NULL,
    net_id    INTEGER NOT NULL REFERENCES net(id),
    lo        INTEGER,
    hi        INTEGER,
    is_exact  INTEGER NOT NULL CHECK(is_exact IN (0,1)),
    UNIQUE(branch_id, ordinal));

-- The gating tree's transitive closure, the level itself included at
-- distance 0. `branch.parent_branch_id` answers one step outward and makes
-- every other question a recursive walk -- and a per-statement question
-- asked through a view that recurses costs 2.4 ms against 3.2 us, because
-- SQLite materialises the whole design's chains before filtering. This is
-- that walk done once, per template, where a module's tree is a few dozen
-- rows; stamping shifts it like every other id.
--
-- Both directions are indexed: fan-in ("what gates this level") on the
-- primary key, fan-out ("what does this level control") on the index beside
-- it, which is a full scan without.
CREATE TABLE branch_ancestor(
    branch_id          INTEGER NOT NULL REFERENCES branch(id),
    ancestor_branch_id INTEGER NOT NULL REFERENCES branch(id),
    distance           INTEGER NOT NULL,
    PRIMARY KEY(branch_id, ancestor_branch_id)) WITHOUT ROWID;


-- One statement, or one statement-level construct. The statement is the
-- object; its targets, operands and other reads are child rows -- v9's
-- `assignment` was one row per TARGET, so `{a,b} = {x,y}` was two rows
-- claiming one statement and a statement writing only outward was no row at
-- all. Here it is one row regardless.
--
-- sequence is execution order within the procedure, NULL outside one (a
-- continuous assign has no execution order) and on the procedure-header
-- event_control row that holds a non-plain sensitivity's reads.
-- assign_kind is NULL for non-assignments. delay is the delay control's
-- normalised source text (`#3`, `#(rise, fall)`), not a number this tool
-- pretended to evaluate; NULL when there is none.
--
-- branch_id is the gating context (`branch`), NULL outside every branch.
-- It is the complete answer to "what gates this statement": the levels above
-- it are `branch_ancestor` from here, their reads are `branch_ref` rows, and
-- a statement kind that records no reads of its own -- an event control --
-- still names its level.
--
-- What is deliberately NOT here: no branch-condition text, no clocked flag,
-- no source text.
--
-- `force` records as a blocking assignment whose construct says 'force'
-- (a procedural `assign` says 'proc_assign') -- the dataflow is a
-- blocking assignment's, and the word is what lets a debugger find the
-- hijack. `release`/`deassign` record as stmt_kind='release' with the
-- lvalue as a target row and deliberately NO dependency: nothing is
-- driven, and the row answers "where does the force end".
CREATE TABLE stmt(
    id                    INTEGER PRIMARY KEY,
    inst_id               INTEGER NOT NULL REFERENCES inst(id),
    scope_node_id         INTEGER NOT NULL REFERENCES tree_node(id),
    proc_id               INTEGER REFERENCES proc(id),
    ordinal               INTEGER NOT NULL,
    sequence              INTEGER,
    stmt_kind             TEXT NOT NULL,
    construct             TEXT,
    assign_kind           TEXT,
    delay                 TEXT,
    dropped_operand_count INTEGER NOT NULL,
    call_site_id          INTEGER REFERENCES call_site(id),
    branch_id             INTEGER REFERENCES branch(id),
    file_id               INTEGER REFERENCES file(id),
    line                  INTEGER,
    col                   INTEGER);

-- One target reference of an assignment (LHS), in written order. A target
-- whose net lies outside the instance is not here -- it is a `hier_ref`
-- with access='write' on the same stmt_id.
CREATE TABLE stmt_target(
    id       INTEGER PRIMARY KEY,
    stmt_id  INTEGER NOT NULL REFERENCES stmt(id),
    ordinal  INTEGER NOT NULL,
    net_id   INTEGER NOT NULL REFERENCES net(id),
    lo       INTEGER,
    hi       INTEGER,
    is_exact INTEGER NOT NULL CHECK(is_exact IN (0,1)),
    UNIQUE(stmt_id, ordinal));

-- One operand reference of an assignment's RHS. Operands belong to the
-- STATEMENT, not to a target: which operand feeds which target is
-- `net_dep`'s answer, and pairing them here would be a cross product. A read
-- occurring twice is two rows.
CREATE TABLE assign_operand(
    id       INTEGER PRIMARY KEY,
    stmt_id  INTEGER NOT NULL REFERENCES stmt(id),
    ordinal  INTEGER NOT NULL,
    net_id   INTEGER NOT NULL REFERENCES net(id),
    lo       INTEGER,
    hi       INTEGER,
    is_exact INTEGER NOT NULL CHECK(is_exact IN (0,1)),
    UNIQUE(stmt_id, ordinal));

-- One statement read that is not an assignment operand, classified by role.
-- A branch condition is not among them: it is read where it is written, so
-- it belongs to its level (`branch_ref`) and not to each statement the level
-- happens to gate.
--
--   assertion      read by an assert/assume/cover/expect
--   wait           a wait statement's condition
--   event          a sensitivity/event expression that is not a plain net
--                  (those are proc_event rows -- one read, one table, never
--                  both, or v_load counts it twice)
--   call_argument  an actual at a call site
--   system_task    read by $display and friends
CREATE TABLE expr_ref(
    id        INTEGER PRIMARY KEY,
    stmt_id   INTEGER NOT NULL REFERENCES stmt(id),
    ordinal   INTEGER NOT NULL,
    net_id    INTEGER NOT NULL REFERENCES net(id),
    role      TEXT NOT NULL,
    lo        INTEGER,
    hi        INTEGER,
    is_exact  INTEGER NOT NULL CHECK(is_exact IN (0,1)),
    UNIQUE(stmt_id, ordinal));

-- One edge event a procedure triggers on or waits on. All of them, because
-- an event list has no order and recording "the first" records how the
-- author arranged the list. Which is the clock is deliberately not decided
-- here, exactly as in v9.
--
-- event_kind='sensitivity' rows belong to the procedure header (stmt_id
-- NULL); event_kind='wait' rows are statement-level controls reached during
-- execution (stmt_id set). net_id is NULL when the event expression is not
-- a plain net -- the reads of such an expression are expr_ref rows with
-- role='event', never both.
CREATE TABLE proc_event(
    id           INTEGER PRIMARY KEY,
    proc_id      INTEGER NOT NULL REFERENCES proc(id),
    stmt_id      INTEGER REFERENCES stmt(id),
    net_id       INTEGER REFERENCES net(id),
    event_kind   TEXT NOT NULL,
    edge_kind    TEXT,
    file_id      INTEGER REFERENCES file(id),
    line         INTEGER,
    col          INTEGER);

-- One net-to-net dependency occurrence -- the adjacency list v_driver and
-- v_load index, and the provenance record v9's deduplicated `edge` erased.
-- NOT deduplicated: the same source reaching the same target from two
-- statements is two rows, each naming its statement. `{a,b} = {x,y}` is
-- x->a and y->b, each naming its operand and target rows -- never the
-- four-way cross product.
--
-- dep_kind, and what must be set for each (verifier-enforced):
--
--   data       an assignment moves it: stmt_id, and per end either the
--              local reference (assign_operand_id / stmt_target_id) or
--              the hierarchical one (src_hier_ref_id / tgt_hier_ref_id).
--              src_net_id NULL with no source reference of either kind is
--              a constant driver (`q <= 8'h0`) -- the row still names the
--              statement, which is what a driver query reports; every
--              src_* column is NULL with it. src_net_id NULL WITH
--              src_hier_ref_id is an external driver: the reference did
--              not resolve to a net row, the source range survives, and
--              v_driver reports 'external'.
--   control    it reaches the target through a branch condition: stmt_id,
--              the level it came from in branch_id -- whose reads are
--              branch_ref rows -- or src_hier_ref_id when the condition
--              names something outside the instance, and the target's
--              reference as above. map_exact is 0: a condition gates, it
--              does not map.
--   primitive  a gate/switch/UDP couples them: prim_id, per LRM
--              (input, output) pairing.
--   procedure  a call binds them: actual to formal by argument direction,
--              and formal back to a written actual. stmt_id is the calling
--              statement (NULL for a call in a control expression); the
--              actual's read is expr_ref_id (role='call_argument') or
--              src_hier_ref_id. A write-back whose formal is no net of this
--              instance -- a subroutine declared in a package, an interface
--              or $unit -- has no source to name, so src_net_id and
--              src_hier_ref_id are both NULL and stmt_target_id names the
--              lvalue instead. That is the only procedure row with no
--              source, and the only one carrying a target row.
--
-- A dependency whose end lies in ANOTHER instance -- `assign q = u.x;`,
-- a write through an interface port -- carries the resolved net id like
-- any other end, and names the hier_ref row it resolved through instead of
-- an operand/target row. The pairing is made where the statement was
-- walked, one row per (source element, target element) that share bits --
-- never by joining hier_ref to operands on stmt_id afterwards, which would
-- be the cross product this pairing avoids. An unresolved TARGET reference
-- produces no dependency: tgt_net_id is NOT NULL, and a guessed written
-- object would be a wrong fact. An unresolved SOURCE reference keeps its
-- row -- src_net_id NULL, src_hier_ref_id set -- because dropping it made
-- "driven through a name this export cannot resolve" indistinguishable
-- from "undriven", which is a wrong fact of the quieter kind.
--
-- src_net_id/tgt_net_id repeat what the referenced rows already
-- know. Deliberate, verified redundancy: this table is the driver/load
-- index, and the verifier holds the copies equal.
CREATE TABLE net_dep(
    id                 INTEGER PRIMARY KEY,
    src_net_id         INTEGER REFERENCES net(id),
    tgt_net_id         INTEGER NOT NULL REFERENCES net(id),
    stmt_id            INTEGER REFERENCES stmt(id),
    assign_operand_id  INTEGER REFERENCES assign_operand(id),
    stmt_target_id   INTEGER REFERENCES stmt_target(id),
    expr_ref_id        INTEGER REFERENCES expr_ref(id),
    -- Control: the level whose condition produced this row. The read itself
    -- is that level's (`branch_ref`); this says which level, where the
    -- columns above name a reference directly.
    branch_id          INTEGER REFERENCES branch(id),
    prim_id            INTEGER REFERENCES prim(id),
    src_hier_ref_id    INTEGER REFERENCES hier_ref(id),
    tgt_hier_ref_id    INTEGER REFERENCES hier_ref(id),
    dep_kind           TEXT NOT NULL,
    src_lo             INTEGER,
    src_hi             INTEGER,
    src_exact          INTEGER CHECK(src_exact IN (0,1)),
    tgt_lo             INTEGER,
    tgt_hi             INTEGER,
    tgt_exact          INTEGER NOT NULL CHECK(tgt_exact IN (0,1)),
    map_exact          INTEGER CHECK(map_exact IN (0,1)),
    call_site_id       INTEGER REFERENCES call_site(id));

-- One reference that leaves the instance: an XMR, an interface member, a
-- package item. The path is stored as written (normalised), AND -- because
-- an occurrence knows its place in the hierarchy where a folded row could
-- not -- resolved to the net it lands on when slang could resolve it and
-- that net is in this export. A NULL resolved_net_id is "not resolved
-- here", never a fabricated object; the instance is that net's own.
--
-- access: read | write | connect (a port connection tied outward; its
-- net_conn row points back here). A reference belongs to the statement it
-- is written in (stmt_id) or, when it is a branch condition, to the level
-- that reads it (branch_id) -- `if (top.dbg_en) …` reads a name outside the
-- instance, so it lands here rather than in branch_ref, and is filed once
-- per level exactly as those are. A connection reference has neither: it is
-- reached through the net_conn row that names it.
CREATE TABLE hier_ref(
    id               INTEGER PRIMARY KEY,
    inst_id          INTEGER NOT NULL REFERENCES inst(id),
    stmt_id          INTEGER REFERENCES stmt(id),
    branch_id        INTEGER REFERENCES branch(id),
    path             TEXT NOT NULL,
    access           TEXT NOT NULL,
    -- The instance is the net's (`net.inst_id`), not a column of its own: a
    -- second spelling of one answer is a pair that can disagree, and twice
    -- did. `v_hier_ref` still publishes it, off the net row it already joins.
    resolved_net_id  INTEGER REFERENCES net(id),
    lo               INTEGER,
    hi               INTEGER,
    is_exact         INTEGER NOT NULL CHECK(is_exact IN (0,1)),
    file_id          INTEGER REFERENCES file(id),
    line             INTEGER,
    col              INTEGER);
